"""planos e assinaturas

Revision ID: 4b98eb171eb9
Revises: fe354343ab52
Create Date: 2026-09-16 02:33:54.061211
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4b98eb171eb9'
down_revision: str | None = 'fe354343ab52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_planos_codigo'))
    )
    op.create_table('assinaturas',
    sa.Column('plano_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('trial', 'ativa', 'inadimplente', 'cancelada', name='status_assinatura', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('trial_termina_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_atual_termina_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carencia_termina_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_assinaturas_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], name=op.f('fk_assinaturas_plano_id_planos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assinaturas')),
    sa.UniqueConstraint('empresa_id', name=op.f('uq_assinaturas_empresa_id'))
    )
    op.create_index(op.f('ix_assinaturas_empresa_id'), 'assinaturas', ['empresa_id'], unique=False)
    op.create_table('plano_regras',
    sa.Column('plano_id', sa.UUID(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('recurso', 'limite', name='tipo_regra', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.CheckConstraint("tipo = 'limite' OR valor IS NULL", name=op.f('ck_plano_regras_recurso_sem_valor')),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], name=op.f('fk_plano_regras_plano_id_planos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plano_id', 'chave', name=op.f('pk_plano_regras'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plano_regras')
    op.drop_index(op.f('ix_assinaturas_empresa_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    op.drop_table('planos')
    # ### end Alembic commands ###
