"""composicao: kits, montados e componentes

`TipoProduto.COMPOSTO` nunca foi utilizável (produtos_service.criar_produto
sempre recusava), então não há linha existente com tipo='composto' para
migrar: só troca o CHECK constraint pelos valores novos (kit, montado).

Também concede a permissão nova de estoque nenhuma (composição reaproveita
produtos.ver/editar e estoque.movimentar) e cadastra o recurso Pro
`perda_na_composicao`, que faltava no seed de planos.

Revision ID: ad2d8b6451e5
Revises: 159532f2102a
Create Date: 2026-09-18 12:27:58.034338
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ad2d8b6451e5'
down_revision: str | None = '159532f2102a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint(op.f('ck_produtos_tipo_produto'), 'produtos', type_='check')
    # Nome passado "cru" (sem o prefixo ck_produtos_): a naming convention da
    # metadata monta o nome final sozinha, senão ele fica duplicado.
    op.create_check_constraint(
        'tipo_produto', 'produtos', "tipo IN ('simples', 'kit', 'montado')"
    )

    op.execute(
        """
        INSERT INTO plano_regras (plano_id, chave, tipo, valor)
        SELECT id, 'perda_na_composicao', 'recurso', NULL FROM planos WHERE codigo = 'pro'
        ON CONFLICT DO NOTHING
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componentes_compostos',
    sa.Column('produto_composto_id', sa.UUID(), nullable=False),
    sa.Column('componente_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('perda_percentual', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['componente_id'], ['produtos.id'], name=op.f('fk_componentes_compostos_componente_id_produtos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_componentes_compostos_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_composto_id'], ['produtos.id'], name=op.f('fk_componentes_compostos_produto_composto_id_produtos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_componentes_compostos')),
    sa.UniqueConstraint('empresa_id', 'produto_composto_id', 'componente_id', name=op.f('uq_componentes_compostos_empresa_id_produto_composto_id_componente_id'))
    )
    op.create_index(op.f('ix_componentes_compostos_componente_id'), 'componentes_compostos', ['componente_id'], unique=False)
    op.create_index(op.f('ix_componentes_compostos_empresa_id'), 'componentes_compostos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_componentes_compostos_produto_composto_id'), 'componentes_compostos', ['produto_composto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_componentes_compostos_produto_composto_id'), table_name='componentes_compostos')
    op.drop_index(op.f('ix_componentes_compostos_empresa_id'), table_name='componentes_compostos')
    op.drop_index(op.f('ix_componentes_compostos_componente_id'), table_name='componentes_compostos')
    op.drop_table('componentes_compostos')
    # ### end Alembic commands ###

    op.execute(
        "DELETE FROM plano_regras WHERE chave = 'perda_na_composicao' "
        "AND plano_id IN (SELECT id FROM planos WHERE codigo = 'pro')"
    )

    op.drop_constraint(op.f('ck_produtos_tipo_produto'), 'produtos', type_='check')
    op.create_check_constraint(
        'tipo_produto', 'produtos', "tipo IN ('simples', 'composto')"
    )
