"""identidade e acesso

Revision ID: fe354343ab52
Revises: 
Create Date: 2026-09-16 02:16:36.870373
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fe354343ab52'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('nome_fantasia', sa.String(length=120), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('documento', sa.String(length=14), nullable=True),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('fuso_horario', sa.String(length=50), server_default='America/Sao_Paulo', nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas')),
    sa.UniqueConstraint('slug', name=op.f('uq_empresas_slug'))
    )
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verificado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_login_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_table('papeis',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('codigo_padrao', sa.String(length=30), nullable=True),
    sa.Column('protegido', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_papeis_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papeis')),
    sa.UniqueConstraint('empresa_id', 'id', name=op.f('uq_papeis_empresa_id_id')),
    sa.UniqueConstraint('empresa_id', 'nome', name=op.f('uq_papeis_empresa_id_nome'))
    )
    op.create_index(op.f('ix_papeis_empresa_id'), 'papeis', ['empresa_id'], unique=False)
    op.create_table('membros',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('papel_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'convidado', 'desativado', name='status_membro', native_enum=False, create_constraint=True, length=20), server_default='ativo', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id', 'papel_id'], ['papeis.empresa_id', 'papeis.id'], name=op.f('fk_membros_empresa_id_papel_id_papeis'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_membros_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_membros_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membros')),
    sa.UniqueConstraint('empresa_id', 'usuario_id', name=op.f('uq_membros_empresa_id_usuario_id'))
    )
    op.create_index(op.f('ix_membros_empresa_id'), 'membros', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_membros_usuario_id'), 'membros', ['usuario_id'], unique=False)
    op.create_table('papel_permissoes',
    sa.Column('papel_id', sa.UUID(), nullable=False),
    sa.Column('permissao', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], name=op.f('fk_papel_permissoes_papel_id_papeis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('papel_id', 'permissao', name=op.f('pk_papel_permissoes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papel_permissoes')
    op.drop_index(op.f('ix_membros_usuario_id'), table_name='membros')
    op.drop_index(op.f('ix_membros_empresa_id'), table_name='membros')
    op.drop_table('membros')
    op.drop_index(op.f('ix_papeis_empresa_id'), table_name='papeis')
    op.drop_table('papeis')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
