"""vendas

Cria as tabelas de vendas (tickets com status aberto/fechado/cancelado) e
concede as permissões novas (vendas.ver, vendas.registrar,
vendas.desconto_acima_limite, vendas.cancelar) aos papéis padrão que já
existem nas empresas criadas antes desta versão. Também define o limite de
desconto percentual do Caixa (10%) — Gerente e Dono ficam sem limite.

Revision ID: 6f8ee0ed2796
Revises: cea5d2178a3e
Create Date: 2026-09-18 22:49:48.498913
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6f8ee0ed2796'
down_revision: str | None = 'cea5d2178a3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Permissões novas por papel padrão (ver acesso/papeis_padrao.py)
PERMISSOES_POR_PAPEL = {
    "gerente": (
        "vendas.ver",
        "vendas.registrar",
        "vendas.desconto_acima_limite",
        "vendas.cancelar",
    ),
    "caixa": ("vendas.ver", "vendas.registrar"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('vendedor_usuario_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.Enum('pdv', 'vitrine', 'marketplace', name='canal_venda', native_enum=False, create_constraint=True, length=20), server_default='pdv', nullable=False),
    sa.Column('status', sa.Enum('aberto', 'fechado', 'cancelado', name='status_venda', native_enum=False, create_constraint=True, length=20), server_default='aberto', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('desconto_total', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_vendas_cliente_id_clientes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_vendas_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendedor_usuario_id'], ['usuarios.id'], name=op.f('fk_vendas_vendedor_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendas')),
    sa.UniqueConstraint('empresa_id', 'id', name=op.f('uq_vendas_empresa_id_id')),
    sa.UniqueConstraint('empresa_id', 'numero', name=op.f('uq_vendas_empresa_id_numero'))
    )
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vendas_empresa_id'), 'vendas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_vendas_status'), 'vendas', ['status'], unique=False)
    op.create_table('itens_venda',
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('movimento_reserva_id', sa.UUID(), nullable=True),
    sa.Column('movimento_estoque_id', sa.UUID(), nullable=True),
    sa.Column('movimento_estorno_id', sa.UUID(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('preco_tabela', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('preco_final', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movimento_estoque_id'], ['movimentacoes_estoque.id'], name=op.f('fk_itens_venda_movimento_estoque_id_movimentacoes_estoque'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimento_estorno_id'], ['movimentacoes_estoque.id'], name=op.f('fk_itens_venda_movimento_estorno_id_movimentacoes_estoque'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimento_reserva_id'], ['movimentacoes_estoque.id'], name=op.f('fk_itens_venda_movimento_reserva_id_movimentacoes_estoque'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_itens_venda_produto_id_produtos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_itens_venda_venda_id_vendas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_venda'))
    )
    op.create_index(op.f('ix_itens_venda_produto_id'), 'itens_venda', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_venda_id'), 'itens_venda', ['venda_id'], unique=False)
    op.create_table('pagamentos_venda',
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('forma', sa.Enum('dinheiro', 'cartao', 'pix', name='forma_pagamento', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_pagamentos_venda_venda_id_vendas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos_venda'))
    )
    op.create_index(op.f('ix_pagamentos_venda_venda_id'), 'pagamentos_venda', ['venda_id'], unique=False)
    op.add_column('papeis', sa.Column('limite_desconto_percentual', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###

    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        for permissao in permissoes:
            op.execute(
                sa.text(
                    """
                    INSERT INTO papel_permissoes (papel_id, permissao)
                    SELECT id, :permissao FROM papeis WHERE codigo_padrao = :codigo_padrao
                    ON CONFLICT DO NOTHING
                    """
                ).bindparams(permissao=permissao, codigo_padrao=codigo_padrao)
            )

    op.execute(
        sa.text(
            "UPDATE papeis SET limite_desconto_percentual = 10 WHERE codigo_padrao = 'caixa'"
        )
    )


def downgrade() -> None:
    op.execute(
        sa.text(
            "UPDATE papeis SET limite_desconto_percentual = NULL WHERE codigo_padrao = 'caixa'"
        )
    )
    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        op.execute(
            sa.text(
                """
                DELETE FROM papel_permissoes
                WHERE permissao = ANY(:permissoes)
                  AND papel_id IN (SELECT id FROM papeis WHERE codigo_padrao = :codigo_padrao)
                """
            ).bindparams(permissoes=list(permissoes), codigo_padrao=codigo_padrao)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papeis', 'limite_desconto_percentual')
    op.drop_index(op.f('ix_pagamentos_venda_venda_id'), table_name='pagamentos_venda')
    op.drop_table('pagamentos_venda')
    op.drop_index(op.f('ix_itens_venda_venda_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_produto_id'), table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_vendas_status'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_empresa_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_table('vendas')
    # ### end Alembic commands ###
