"""sessoes

Revision ID: c31af376217c
Revises: a7c3e9d2f410
Create Date: 2026-09-16 02:51:52.526022
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c31af376217c'
down_revision: str | None = 'a7c3e9d2f410'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_uso_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_sessoes_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_sessoes_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessoes'))
    )
    op.create_index(op.f('ix_sessoes_usuario_id'), 'sessoes', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_usuario_id'), table_name='sessoes')
    op.drop_table('sessoes')
    # ### end Alembic commands ###
