"""produtos e unidades

Revision ID: e73bc431d3d1
Revises: c31af376217c
Create Date: 2026-09-17 18:10:48.835483
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e73bc431d3d1'
down_revision: str | None = 'c31af376217c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('grandeza', sa.String(length=20), nullable=False),
    sa.Column('fator_canonico', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('casas_exibidas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('codigo', name=op.f('pk_unidades'))
    )
    op.create_table('categorias',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('categoria_pai_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_categorias_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias')),
    sa.UniqueConstraint('empresa_id', 'id', name=op.f('uq_categorias_empresa_id_id')),
    sa.UniqueConstraint('empresa_id', 'nome', name=op.f('uq_categorias_empresa_id_nome'))
    )
    op.create_index(op.f('ix_categorias_empresa_id'), 'categorias', ['empresa_id'], unique=False)
    op.create_table('produtos',
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('simples', 'composto', name='tipo_produto', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'congelado', name='status_produto', native_enum=False, create_constraint=True, length=20), server_default='ativo', nullable=False),
    sa.Column('unidade_codigo', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('vendavel', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('insumo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('controla_estoque', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo_medio', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('custo_ultima_compra', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('codigo_barras', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('publicado_na_vitrine', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('descricao_publica', sa.String(length=2000), nullable=True),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('cest', sa.String(length=7), nullable=True),
    sa.Column('origem', sa.String(length=1), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_produtos_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unidade_codigo'], ['unidades.codigo'], name=op.f('fk_produtos_unidade_codigo_unidades'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produtos')),
    sa.UniqueConstraint('empresa_id', 'id', name=op.f('uq_produtos_empresa_id_id')),
    sa.UniqueConstraint('empresa_id', 'sku', name=op.f('uq_produtos_empresa_id_sku'))
    )
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=False)
    op.create_index(op.f('ix_produtos_empresa_id'), 'produtos', ['empresa_id'], unique=False)
    op.create_table('produto_unidades',
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('fator', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('usa_na_compra', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('usa_na_venda', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_produto_unidades_produto_id_produtos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produto_unidades')),
    sa.UniqueConstraint('produto_id', 'nome', name=op.f('uq_produto_unidades_produto_id_nome'))
    )
    op.create_index(op.f('ix_produto_unidades_produto_id'), 'produto_unidades', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_unidades_produto_id'), table_name='produto_unidades')
    op.drop_table('produto_unidades')
    op.drop_index(op.f('ix_produtos_empresa_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_categorias_empresa_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_table('unidades')
    # ### end Alembic commands ###
