"""estoque: movimentacoes e saldos

Cria as tabelas de estoque e concede as permissões novas (estoque.ver,
estoque.movimentar, estoque.ajustar) aos papéis padrão que já existem
nas empresas criadas antes desta versão.

Revision ID: 159532f2102a
Revises: b2d5f8a1c934
Create Date: 2026-09-18 11:49:58.322262
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '159532f2102a'
down_revision: str | None = 'b2d5f8a1c934'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Permissões novas por papel padrão (ver acesso/papeis_padrao.py)
PERMISSOES_POR_PAPEL = {
    "gerente": ("estoque.ver", "estoque.movimentar", "estoque.ajustar"),
    "caixa": ("estoque.ver",),
    "estoquista": ("estoque.ver", "estoque.movimentar", "estoque.ajustar"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes_estoque',
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', 'ajuste', 'montagem', 'reserva', 'liberacao', name='tipo_movimento', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('origem', sa.String(length=60), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_movimentacoes_estoque_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_movimentacoes_estoque_produto_id_produtos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacoes_estoque')),
    sa.UniqueConstraint('empresa_id', 'id', name=op.f('uq_movimentacoes_estoque_empresa_id_id'))
    )
    op.create_index(op.f('ix_movimentacoes_estoque_empresa_id'), 'movimentacoes_estoque', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_produto_id'), 'movimentacoes_estoque', ['produto_id'], unique=False)
    op.create_table('saldos_estoque',
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('fisico', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('reservado', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_saldos_estoque_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_saldos_estoque_produto_id_produtos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saldos_estoque')),
    sa.UniqueConstraint('empresa_id', 'produto_id', name=op.f('uq_saldos_estoque_empresa_id_produto_id'))
    )
    op.create_index(op.f('ix_saldos_estoque_empresa_id'), 'saldos_estoque', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_saldos_estoque_produto_id'), 'saldos_estoque', ['produto_id'], unique=False)
    # ### end Alembic commands ###

    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        for permissao in permissoes:
            op.execute(
                sa.text(
                    """
                    INSERT INTO papel_permissoes (papel_id, permissao)
                    SELECT id, :permissao FROM papeis WHERE codigo_padrao = :codigo_padrao
                    ON CONFLICT DO NOTHING
                    """
                ).bindparams(permissao=permissao, codigo_padrao=codigo_padrao)
            )


def downgrade() -> None:
    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        op.execute(
            sa.text(
                """
                DELETE FROM papel_permissoes
                WHERE permissao = ANY(:permissoes)
                  AND papel_id IN (SELECT id FROM papeis WHERE codigo_padrao = :codigo_padrao)
                """
            ).bindparams(permissoes=list(permissoes), codigo_padrao=codigo_padrao)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saldos_estoque_produto_id'), table_name='saldos_estoque')
    op.drop_index(op.f('ix_saldos_estoque_empresa_id'), table_name='saldos_estoque')
    op.drop_table('saldos_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_produto_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_empresa_id'), table_name='movimentacoes_estoque')
    op.drop_table('movimentacoes_estoque')
    # ### end Alembic commands ###
