"""clientes

Cria a tabela de clientes e concede as permissões novas (clientes.ver,
clientes.editar) aos papéis padrão que já existem nas empresas criadas
antes desta versão.

Revision ID: cea5d2178a3e
Revises: bb2e2d7f6e12
Create Date: 2026-09-18 17:29:50.014480
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cea5d2178a3e'
down_revision: str | None = 'bb2e2d7f6e12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Permissões novas por papel padrão (ver acesso/papeis_padrao.py)
PERMISSOES_POR_PAPEL = {
    "gerente": ("clientes.ver", "clientes.editar"),
    "caixa": ("clientes.ver", "clientes.editar"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('consentimento_marketing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origem', sa.Enum('balcao', 'vitrine', 'marketplace', name='origem_cliente', native_enum=False, create_constraint=True, length=20), server_default='balcao', nullable=False),
    sa.Column('anonimizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_clientes_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes')),
    sa.UniqueConstraint('empresa_id', 'id', name=op.f('uq_clientes_empresa_id_id'))
    )
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_clientes_telefone'), 'clientes', ['telefone'], unique=False)
    # ### end Alembic commands ###

    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        for permissao in permissoes:
            op.execute(
                sa.text(
                    """
                    INSERT INTO papel_permissoes (papel_id, permissao)
                    SELECT id, :permissao FROM papeis WHERE codigo_padrao = :codigo_padrao
                    ON CONFLICT DO NOTHING
                    """
                ).bindparams(permissao=permissao, codigo_padrao=codigo_padrao)
            )


def downgrade() -> None:
    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        op.execute(
            sa.text(
                """
                DELETE FROM papel_permissoes
                WHERE permissao = ANY(:permissoes)
                  AND papel_id IN (SELECT id FROM papeis WHERE codigo_padrao = :codigo_padrao)
                """
            ).bindparams(permissoes=list(permissoes), codigo_padrao=codigo_padrao)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_telefone'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
