"""caixa do dia

Cria as tabelas do caixa do dia (sessão + lançamentos) e concede as
permissões novas (financeiro.ver, financeiro.operar) aos papéis padrão que
já existem nas empresas criadas antes desta versão.

Revision ID: 09708ecf13e7
Revises: e4f53c0ab667
Create Date: 2026-09-19 00:06:34.215444
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '09708ecf13e7'
down_revision: str | None = 'e4f53c0ab667'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Permissões novas por papel padrão (ver acesso/papeis_padrao.py)
PERMISSOES_POR_PAPEL = {
    "gerente": ("financeiro.ver", "financeiro.operar"),
    "caixa": ("financeiro.ver", "financeiro.operar"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixas_sessao',
    sa.Column('aberto_por_usuario_id', sa.UUID(), nullable=False),
    sa.Column('fechado_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('aberto', 'fechado', name='status_caixa', native_enum=False, create_constraint=True, length=20), server_default='aberto', nullable=False),
    sa.Column('valor_inicial', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_contado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('aberto_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aberto_por_usuario_id'], ['usuarios.id'], name=op.f('fk_caixas_sessao_aberto_por_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_caixas_sessao_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fechado_por_usuario_id'], ['usuarios.id'], name=op.f('fk_caixas_sessao_fechado_por_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caixas_sessao')),
    sa.UniqueConstraint('empresa_id', 'id', name=op.f('uq_caixas_sessao_empresa_id_id'))
    )
    op.create_index(op.f('ix_caixas_sessao_empresa_id'), 'caixas_sessao', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_caixas_sessao_status'), 'caixas_sessao', ['status'], unique=False)
    op.create_table('lancamentos_caixa',
    sa.Column('caixa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipo_lancamento', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('origem', sa.Enum('venda', 'manual', name='origem_lancamento', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('dinheiro', 'cartao', 'pix', name='forma_pagamento_lancamento', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('venda_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas_sessao.id'], name=op.f('fk_lancamentos_caixa_caixa_id_caixas_sessao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_lancamentos_caixa_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_lancamentos_caixa_venda_id_vendas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lancamentos_caixa'))
    )
    op.create_index(op.f('ix_lancamentos_caixa_caixa_id'), 'lancamentos_caixa', ['caixa_id'], unique=False)
    # ### end Alembic commands ###

    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        for permissao in permissoes:
            op.execute(
                sa.text(
                    """
                    INSERT INTO papel_permissoes (papel_id, permissao)
                    SELECT id, :permissao FROM papeis WHERE codigo_padrao = :codigo_padrao
                    ON CONFLICT DO NOTHING
                    """
                ).bindparams(permissao=permissao, codigo_padrao=codigo_padrao)
            )


def downgrade() -> None:
    for codigo_padrao, permissoes in PERMISSOES_POR_PAPEL.items():
        op.execute(
            sa.text(
                """
                DELETE FROM papel_permissoes
                WHERE permissao = ANY(:permissoes)
                  AND papel_id IN (SELECT id FROM papeis WHERE codigo_padrao = :codigo_padrao)
                """
            ).bindparams(permissoes=list(permissoes), codigo_padrao=codigo_padrao)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamentos_caixa_caixa_id'), table_name='lancamentos_caixa')
    op.drop_table('lancamentos_caixa')
    op.drop_index(op.f('ix_caixas_sessao_status'), table_name='caixas_sessao')
    op.drop_index(op.f('ix_caixas_sessao_empresa_id'), table_name='caixas_sessao')
    op.drop_table('caixas_sessao')
    # ### end Alembic commands ###
