"""mesclagem de clientes

Revision ID: e4f53c0ab667
Revises: 9cd65cef8fd7
Create Date: 2026-09-18 22:54:44.471372
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e4f53c0ab667'
down_revision: str | None = '9cd65cef8fd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('mesclado_com_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_clientes_mesclado_com_id_clientes'), 'clientes', 'clientes', ['mesclado_com_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_clientes_mesclado_com_id_clientes'), 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'mesclado_com_id')
    # ### end Alembic commands ###
