"""producao: tempo de preparo, recursos produtivos e custos adicionais

Migração de dados: cadastra o recurso `capacidade_producao` no plano Pro
(faltava desde o seed original — `custos_adicionais` já existia lá, sem uso
até agora).

Revision ID: bb2e2d7f6e12
Revises: f3a6c9e2b810
Create Date: 2026-09-18 16:44:57.343182
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bb2e2d7f6e12'
down_revision: str | None = 'f3a6c9e2b810'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos_produtivos',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('tipo', sa.Enum('pessoa', 'maquina', name='tipo_recurso', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), server_default='1', nullable=False),
    sa.Column('horas_disponiveis_por_dia', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('custo_por_hora', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_recursos_produtivos_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recursos_produtivos')),
    sa.UniqueConstraint('empresa_id', 'nome', name=op.f('uq_recursos_produtivos_empresa_id_nome'))
    )
    op.create_index(op.f('ix_recursos_produtivos_empresa_id'), 'recursos_produtivos', ['empresa_id'], unique=False)
    op.create_table('custos_adicionais_produto',
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_custos_adicionais_produto_produto_id_produtos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custos_adicionais_produto')),
    sa.UniqueConstraint('produto_id', 'nome', name=op.f('uq_custos_adicionais_produto_produto_id_nome'))
    )
    op.create_index(op.f('ix_custos_adicionais_produto_produto_id'), 'custos_adicionais_produto', ['produto_id'], unique=False)
    op.create_table('producao_produtos',
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('tempo_ativo_minutos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tempo_maquina_minutos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rendimento_lote', sa.Numeric(precision=10, scale=4), server_default='1', nullable=False),
    sa.Column('recurso_maquina_id', sa.UUID(), nullable=True),
    sa.Column('recurso_pessoa_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_producao_produtos_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_producao_produtos_produto_id_produtos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_maquina_id'], ['recursos_produtivos.id'], name=op.f('fk_producao_produtos_recurso_maquina_id_recursos_produtivos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurso_pessoa_id'], ['recursos_produtivos.id'], name=op.f('fk_producao_produtos_recurso_pessoa_id_recursos_produtivos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producao_produtos')),
    sa.UniqueConstraint('empresa_id', 'produto_id', name=op.f('uq_producao_produtos_empresa_id_produto_id'))
    )
    op.create_index(op.f('ix_producao_produtos_empresa_id'), 'producao_produtos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_producao_produtos_produto_id'), 'producao_produtos', ['produto_id'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO plano_regras (plano_id, chave, tipo, valor)
        SELECT id, 'capacidade_producao', 'recurso', NULL FROM planos WHERE codigo = 'pro'
        ON CONFLICT DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM plano_regras WHERE chave = 'capacidade_producao' "
        "AND plano_id IN (SELECT id FROM planos WHERE codigo = 'pro')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producao_produtos_produto_id'), table_name='producao_produtos')
    op.drop_index(op.f('ix_producao_produtos_empresa_id'), table_name='producao_produtos')
    op.drop_table('producao_produtos')
    op.drop_index(op.f('ix_custos_adicionais_produto_produto_id'), table_name='custos_adicionais_produto')
    op.drop_table('custos_adicionais_produto')
    op.drop_index(op.f('ix_recursos_produtivos_empresa_id'), table_name='recursos_produtivos')
    op.drop_table('recursos_produtivos')
    # ### end Alembic commands ###
